// Arabic page copy for the shared page views, with the same shape as lib/content/pages.ts.
import type { PagesCopy } from '../pages'
import type { PageSeo } from '../../seo-pages'

const count = (n: number, one: string, two: string, few: string, many: string) => (n === 1 ? one : n === 2 ? two : n <= 10 ? `${n} ${few}` : `${n} ${many}`)

export const arPages: PagesCopy = {
  about: {
    crumb: 'عن الشركة',
    title: 'شريك موثوق لقطاعات علوم الحياة.',
    facts: ['تأسيس المجموعة', 'أسواق نعمل فيها', 'أقسام متخصصة', 'شركاء مصنّعون'],
    primary: 'تحدث إلى أحد المختصين',
    secondary: 'شركاؤنا',
    heritageTitle: 'نستند إلى مجموعة ذات سجل حافل.',
    based: 'يقع مقر عرب لاب في رأس الخيمة، وتخدم قطاعي الأدوية والمستحضرات الحيوية وقطاع المختبرات في أنحاء المنطقة.',
    leadership: 'القيادة',
    mission: 'رسالتنا',
    faqTitle: 'عن عرب لاب: الأسئلة الشائعة',
    faq: [
      { q: 'هل عرب لاب للمعدات العلمية هي نفسها معرض ARABLAB؟', a: 'لا. عرب لاب للمعدات العلمية ذ.م.م شركة توفر حلول المختبرات ومراقبة الجودة الدوائية والمعالجة الحيوية، ومقرها الرئيسي في رأس الخيمة. أما ARABLAB، المعروف أيضاً باسم ARABLAB LIVE، فهو معرض تجاري لقطاع المختبرات.' },
      { q: 'أين يقع المقر الرئيسي لعرب لاب؟', a: 'في 408، برج جلفار، شارع الحصن، رأس الخيمة، الإمارات العربية المتحدة، مع مكتبين في الرياض والقاهرة.' },
      { q: 'ما علاقة عرب لاب بمجموعة GEO-Science؟', a: 'عرب لاب شركة شقيقة لمجموعة GEO-Science التي تأسست عام 2001 في أبوظبي.' },
      { q: 'ما القطاعات التي تخدمها عرب لاب؟', a: 'مصنّعو الأدوية والأدوية الحيوية، ومختبرات البحث والتطوير، والمختبرات الكيميائية ومختبرات علم الأمراض، في مجالات علوم الحياة والتشخيص والأغذية والمشروبات.' },
    ],
    coverageTitle: 'قريبون من مختبرك.',
    coverageIntro: (n, markets) => `${count(n, 'مكتب واحد', 'مكتبان', 'مكاتب', 'مكتباً')} في ${markets}.`,
  },
  brands: {
    crumb: 'العلامات التجارية',
    title: 'سبعة شركاء. برنامج واحد.',
    intro: 'يعالج كل شريك مصنّع مشكلة مخبرية محددة، من اختبار العقم السريع إلى الترشيح في العمليات وأوساط الاستنبات.',
    primary: 'ناقش تطبيقك معنا',
    secondary: 'تصفح حسب المشكلة',
    countTitle: (n) => `${n} شركاء متخصصين.`,
    accent: 'ناقش تطبيقك معنا',
    matchedTitle: 'كل شريك لمشكلة مخبرية محددة.',
    supplier: 'مورّد في الإمارات والسعودية ومصر',
    allPartners: 'جميع الشركاء',
    atAGlance: 'لمحة سريعة',
    solves: 'يعالج',
    categoriesTitle: (name) => `فئات منتجات ${name}`,
    categoriesIntro: (name) => `المجالات الرئيسية في محفظة ${name}. اسألنا عن المجموعة المتاحة حالياً في بلدك.`,
    bringsTitle: (name) => `ما تقدّمه ${name} للمختبر.`,
    applicationsTitle: 'التطبيقات والقطاعات',
    fitsTitle: (name) => `موقع ${name} في حلولنا`,
    fitsIntro: (n) => (n === 1 ? 'حل عرب لاب الذي يخدمه هذا الشريك:' : 'حلول عرب لاب التي يخدمها هذا الشريك:'),
    availableTitle: 'متاح في الإمارات والسعودية ومصر',
    availableIntro: (name) => `يتولى طلبات ${name} مكتب عرب لاب الذي يغطي بلدك.`,
    hq: 'المقر الرئيسي',
    faqTitle: (name) => `${name}: الأسئلة الشائعة`,
    quote: (name) => `اطلب عرض سعر لمنتجات ${name}`,
    browse: 'تصفح الحلول',
    restTitle: 'بقية المحفظة.',
    allBrands: 'جميع العلامات',
  },
  solutions: {
    crumb: 'الحلول',
    title: 'حلول منظمة حسب المشكلة لا حسب الشركة المصنّعة.',
    intro: 'يُصاغ كل حل حول ما يحتاج مختبرك إلى اختباره أو تصنيعه أو الإفراج عنه، ويرتبط بالشريك الذي تعالج تقنيته هذه المشكلة.',
    primary: 'صف تطبيقك',
    secondary: 'تعرّف على الشركاء',
    countTitle: 'ست مشكلات، وسبعة شركاء.',
    guide: 'اقرأ الدليل الكامل',
    servicesTitle: 'أربعة خطوط خدمة.',
    quote: 'اطلب عرض سعر',
    aboutPartner: (name) => `عن ${name}`,
    partnerBrands: 'العلامات الشريكة',
    whoFor: 'لمن هذا الحل',
    serviceLines: 'خطوط الخدمة',
    partnersTitle: 'تقنية الشركاء',
    faqTitle: 'الأسئلة الشائعة',
    askSpecialist: 'اسأل أحد المختصين',
    relatedTitle: 'حلول ذات صلة',
  },
  services: {
    crumb: 'الخدمات',
    title: 'أربعة خطوط خدمة للأدوية والأغذية والمختبرات الجديدة.',
    intro: 'من معدات مراقبة الجودة إلى مشاريع المختبرات المتكاملة والاستشارات التنظيمية، يدير كل خط خدمة أقسام عرب لاب المتخصصة فيه.',
    primary: 'تحدث إلى أحد المختصين',
    secondary: 'تصفح الحلول',
    linesTitle: 'خطوط الخدمة لدينا',
    behindTitle: 'الحلول التي تقوم عليها',
    behindIntro: 'ست مشكلات مخبرية، يعالج كلاً منها شريك مصنّع.',
    allServices: 'جميع الخدمات',
    inLineTitle: 'الحلول ضمن هذا الخط',
    teamsTitle: 'الفرق التي تقف خلفه',
    teamsIntro: 'يُوجَّه كل طلب إلى قسم عرب لاب المختص به.',
    faqTitle: 'الأسئلة الشائعة',
    otherTitle: 'خطوط الخدمة الأخرى',
  },
  blogCategory: {
    crumb: 'المدونة',
    seoTitle: (name) => `مقالات ${name}`,
    count: (n) => count(n, 'مقال واحد', 'مقالان', 'مقالات', 'مقالاً'),
    all: 'جميع المقالات',
  },
}

/** Search copy for the Arabic static pages (titles take the " | عرب لاب" suffix from the Arabic root layout). */
export const arPageSeo: Record<'/about' | '/solutions' | '/brands', PageSeo> = {
  '/about': {
    title: 'عن عرب لاب للمعدات العلمية | رأس الخيمة، الإمارات', absoluteTitle: true,
    description: 'عرب لاب للمعدات العلمية، الشركة الشقيقة لمجموعة GEO-Science، تخدم عملاء الأدوية والتقنية الحيوية والمختبرات من رأس الخيمة والرياض والقاهرة.',
    ogAlt: 'عن عرب لاب للمعدات العلمية، ومقرها الرئيسي في رأس الخيمة، الإمارات',
    card: { kicker: 'About Arab Lab', title: 'A trusted partner for Life Science industries.' },
  },
  '/solutions': {
    title: 'حلول المختبرات في الإمارات والسعودية ومصر',
    description: 'حلول مخبرية منظمة حسب المشكلة التي تعالجها: اختبار العقم السريع، واختبار الإندوتوكسين، والترشيح، ومناولة السوائل، وأوساط الاستنبات، والإنزيمات.',
    ogAlt: 'حلول عرب لاب للمختبرات: العقم والإندوتوكسين والترشيح ومناولة السوائل والأوساط والإنزيمات',
    card: { kicker: 'Solutions', title: 'Organised by the problem, not the manufacturer.' },
  },
  '/brands': {
    title: 'العلامات الشريكة: Eppendorf وLonza وParker وغيرها',
    description: 'سبعة شركاء مصنّعين من عرب لاب في الإمارات والسعودية ومصر: Eppendorf وParker وLonza وPromicol وPMM وCPC Biotech وTailin.',
    ogAlt: 'العلامات الشريكة لعرب لاب: Eppendorf وParker وLonza وPromicol وPMM وCPC Biotech وTailin',
    card: { kicker: 'Partner brands', title: 'Seven partners. One program.' },
  },
}
