// Primary target keyword per route (mirrors the keyword map in docs/seo/SEO-CONTEXT.md). Used by the audit report.
export const keywordFor: Record<string, string> = {
  '/': 'Arab Lab Scientific Equipment',
  '/about': 'Arab Lab Scientific Equipment company',
  '/solutions': 'laboratory solutions UAE',
  '/solutions/rapid-sterility-testing': 'rapid sterility testing',
  '/solutions/endotoxin-testing': 'endotoxin testing',
  '/solutions/process-filtration-single-use': 'sterile filtration pharmaceutical',
  '/solutions/liquid-handling-bioprocess': 'liquid handling equipment UAE',
  '/solutions/pharmaceutical-culture-media': 'pharmaceutical culture media',
  '/solutions/enzymatic-qc-reagents': 'enzymatic QC reagents',
  '/services': 'laboratory services UAE',
  '/services/pharma-biotech': 'pharma and biotech lab solutions UAE',
  '/services/food-beverage': 'food testing lab equipment UAE',
  '/services/turnkey-projects': 'turnkey laboratory project UAE',
  '/services/pharmaceutical-consultant': 'pharmaceutical regulatory consultant Saudi Arabia',
  '/brands': 'laboratory brands supplier UAE',
  '/brands/eppendorf': 'Eppendorf supplier UAE',
  '/brands/parker': 'Parker supplier UAE',
  '/brands/lonza': 'Lonza supplier UAE',
  '/brands/promicol': 'Promicol supplier UAE',
  '/brands/pmm': 'PMM supplier UAE',
  '/brands/cpc-biotech': 'CPC Biotech supplier UAE',
  '/brands/tailin': 'Tailin supplier UAE',
  '/locations': 'Arab Lab offices',
  '/locations/ras-al-khaimah': 'Arab Lab Ras Al Khaimah',
  '/locations/riyadh': 'Arab Lab Riyadh',
  '/locations/cairo': 'Arab Lab Cairo',
  '/contact': 'contact Arab Lab',
  '/blog': 'laboratory insights',
  '/privacy': '—',
  '/terms': '—',
  '/data-collection': '—',
  '/ar': 'عرب لاب',
  '/ar/contact': 'تواصل مع عرب لاب',
  '/ar/locations': 'مكاتب عرب لاب',
  '/ar/locations/ras-al-khaimah': 'عرب لاب رأس الخيمة',
  '/ar/locations/riyadh': 'عرب لاب الرياض',
  '/ar/locations/cairo': 'عرب لاب القاهرة',
  '/ar/blog': 'مقالات المختبرات',
}
